export type ExerciseCategory = "core" | "forza" | "schiena" | "mobilita" | "cardio";

export type PoseTarget = "squat" | "pushup" | "plank" | "lunge" | "crunch" | "any";

export interface Exercise {
  id: string;
  name: string;
  category: ExerciseCategory;
  short: string;
  description: string;
  steps: string[];
  tips: string[];
  workSeconds: number;
  restSeconds: number;
  rounds: number;
  poseTarget: PoseTarget;
  emoji: string;
}

export const CATEGORIES: {
  id: ExerciseCategory;
  title: string;
  subtitle: string;
  emoji: string;
}[] = [
  { id: "core", title: "Core", subtitle: "Addominali e stabilità", emoji: "🔥" },
  { id: "forza", title: "Sviluppo muscolare", subtitle: "Forza a corpo libero", emoji: "💪" },
  { id: "schiena", title: "Mal di schiena", subtitle: "Esercizi terapeutici", emoji: "🧘" },
  { id: "mobilita", title: "Mobilità", subtitle: "Articolazioni e flessibilità", emoji: "🤸" },
  { id: "cardio", title: "Cardio", subtitle: "Resistenza e fiato", emoji: "🏃‍♂️" },
];

export const EXERCISES: Exercise[] = [
  {
    id: "plank",
    name: "Plank",
    category: "core",
    short: "Isometrico per addominali profondi",
    description:
      "Posizione isometrica che attiva tutto il core, le spalle e i glutei. Fondamentale per la stabilità del tronco.",
    steps: [
      "Mettiti in posizione prona, appoggiando avambracci e punte dei piedi.",
      "Gomiti sotto le spalle, sguardo a terra, collo allineato alla colonna.",
      "Contrai addominali e glutei mantenendo il corpo in linea retta.",
      "Respira lentamente senza far cadere i fianchi.",
    ],
    tips: [
      "Non sollevare il bacino",
      "Non incurvare la schiena",
      "Mantieni la respirazione costante",
    ],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "plank",
    emoji: "🪵",
  },
  {
    id: "crunch",
    name: "Crunch",
    category: "core",
    short: "Classico per il retto addominale",
    description: "Esercizio mirato per il retto addominale, eseguito con movimento controllato.",
    steps: [
      "Sdraiati supino, ginocchia piegate e piedi a terra.",
      "Mani dietro la nuca senza tirare il collo.",
      "Solleva le spalle dal pavimento contraendo gli addominali.",
      "Torna lentamente alla posizione iniziale.",
    ],
    tips: ["Espira mentre sali", "Non staccare la zona lombare", "Movimento lento e controllato"],
    workSeconds: 35,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "crunch",
    emoji: "🧎",
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    category: "core",
    short: "Dinamico per core e cardio",
    description:
      "Esercizio dinamico che combina lavoro per il core con attivazione cardiovascolare.",
    steps: [
      "Parti in posizione di plank alto, braccia tese sotto le spalle.",
      "Porta alternativamente un ginocchio verso il petto.",
      "Mantieni i fianchi bassi e il core contratto.",
      "Accelera il ritmo mantenendo la tecnica.",
    ],
    tips: ["Spalle sopra ai polsi", "Non alzare il bacino", "Respira ritmicamente"],
    workSeconds: 30,
    restSeconds: 25,
    rounds: 3,
    poseTarget: "any",
    emoji: "🏔️",
  },
  {
    id: "squat",
    name: "Squat",
    category: "forza",
    short: "Re degli esercizi per le gambe",
    description:
      "Esercizio fondamentale per quadricipiti, glutei e core. Migliora forza e mobilità delle gambe.",
    steps: [
      "Piedi alla larghezza delle spalle, punte leggermente in fuori.",
      "Scendi piegando ginocchia e anche come se ti sedessi.",
      "Le ginocchia seguono la direzione delle punte dei piedi.",
      "Scendi fino a portare le cosce parallele al pavimento e risali.",
    ],
    tips: ["Petto alto e schiena dritta", "Peso sui talloni", "Ginocchia in linea con i piedi"],
    workSeconds: 40,
    restSeconds: 25,
    rounds: 4,
    poseTarget: "squat",
    emoji: "🦵",
  },
  {
    id: "pushup",
    name: "Piegamenti",
    category: "forza",
    short: "Pettorali, spalle e tricipiti",
    description:
      "Esercizio classico per la parte alta del corpo. Allena pettorali, deltoidi anteriori, tricipiti e core.",
    steps: [
      "Posizione prona, mani a terra leggermente più larghe delle spalle.",
      "Corpo in linea retta dalla testa ai talloni.",
      "Scendi piegando i gomiti fino a sfiorare il petto a terra.",
      "Spingi tornando alla posizione di partenza.",
    ],
    tips: [
      "Non far cadere i fianchi",
      "Gomiti a circa 45°",
      "Contrai il core durante tutto il movimento",
    ],
    workSeconds: 35,
    restSeconds: 25,
    rounds: 4,
    poseTarget: "pushup",
    emoji: "🙇",
  },
  {
    id: "lunge",
    name: "Affondi",
    category: "forza",
    short: "Gambe e glutei in alternato",
    description:
      "Esercizio unilaterale per gambe e glutei che migliora anche equilibrio e coordinazione.",
    steps: [
      "In piedi, fai un passo avanti con una gamba.",
      "Piega entrambe le ginocchia fino a circa 90°.",
      "Il ginocchio posteriore sfiora il pavimento.",
      "Spingi sul tallone anteriore per tornare in piedi e alterna.",
    ],
    tips: ["Busto eretto", "Ginocchio anteriore non oltre la punta", "Movimento controllato"],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "lunge",
    emoji: "🚶",
  },
  {
    id: "cat-cow",
    name: "Gatto-Mucca",
    category: "schiena",
    short: "Mobilizzazione della colonna",
    description:
      "Esercizio dolce di mobilità per la colonna vertebrale. Allevia tensioni lombari e dorsali.",
    steps: [
      "Posizione quadrupedica, mani sotto le spalle e ginocchia sotto le anche.",
      "Inspira inarcando la schiena verso terra (mucca).",
      "Espira incurvando la colonna verso l'alto (gatto).",
      "Esegui il movimento lentamente seguendo il respiro.",
    ],
    tips: ["Movimento fluido", "Sincronizza con il respiro", "Nessun dolore acuto"],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🐱",
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    category: "schiena",
    short: "Stabilità lombare",
    description:
      "Esercizio terapeutico molto efficace contro il mal di schiena lombare. Allena il core profondo.",
    steps: [
      "Quadrupedia, schiena neutra.",
      "Estendi contemporaneamente braccio destro e gamba sinistra.",
      "Mantieni 2 secondi mantenendo bacino stabile.",
      "Torna lentamente e alterna.",
    ],
    tips: ["Non ruotare il bacino", "Movimento lento", "Contrai gli addominali"],
    workSeconds: 45,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🐦",
  },
  {
    id: "glute-bridge",
    name: "Ponte glutei",
    category: "schiena",
    short: "Glutei e zona lombare",
    description: "Rinforza i glutei e la zona lombare, riducendo il carico sulla schiena.",
    steps: [
      "Supino, ginocchia piegate, piedi a terra alla larghezza dei fianchi.",
      "Spingi sui talloni sollevando il bacino.",
      "Contrai i glutei in alto per 2 secondi.",
      "Scendi lentamente senza appoggiare completamente.",
    ],
    tips: ["Non inarcare troppo la lombare", "Stringi i glutei in alto", "Piedi ben piantati"],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🌉",
  },
  {
    id: "neck-stretch",
    name: "Allungamento collo",
    category: "mobilita",
    short: "Per cervicale e spalle",
    description: "Allunga i muscoli del collo, perfetto dopo ore al computer.",
    steps: [
      "Seduto o in piedi, schiena dritta.",
      "Inclina lentamente la testa verso una spalla.",
      "Mantieni 15 secondi sentendo l'allungamento.",
      "Cambia lato.",
    ],
    tips: ["Movimenti lenti", "Spalle rilassate", "Niente dolore"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "💆",
  },
  {
    id: "hip-opener",
    name: "Apertura anche",
    category: "mobilita",
    short: "Mobilità del bacino",
    description: "Migliora la mobilità delle anche, fondamentale per chi sta seduto a lungo.",
    steps: [
      "Quadrupedia, porta un piede tra le mani.",
      "Allunga la gamba posteriore indietro.",
      "Spingi delicatamente il bacino verso il basso.",
      "Mantieni la posizione e cambia lato.",
    ],
    tips: ["Respira profondamente", "Niente dolore acuto", "Apri il petto"],
    workSeconds: 40,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🧘‍♂️",
  },
  // ============ CORE ============
  {
    id: "russian-twist",
    name: "Russian Twist",
    category: "core",
    short: "Obliqui e rotazione del tronco",
    description:
      "Esercizio mirato per i muscoli obliqui. Migliora la forza rotazionale del core e la stabilità del tronco.",
    steps: [
      "Siediti a terra, ginocchia piegate e talloni appoggiati o sollevati.",
      "Inclina il busto indietro di circa 45° mantenendo la schiena dritta.",
      "Intreccia le mani davanti al petto o tieni un peso.",
      "Ruota il tronco a destra e poi a sinistra alternando con controllo.",
    ],
    tips: [
      "Movimento dal tronco, non dalle braccia",
      "Schiena dritta",
      "Respira ad ogni rotazione",
    ],
    workSeconds: 35,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🌀",
  },
  {
    id: "leg-raise",
    name: "Sollevamento gambe",
    category: "core",
    short: "Addominali bassi",
    description:
      "Isolamento del retto addominale inferiore. Ottimo per definire la parte bassa dell'addome.",
    steps: [
      "Sdraiati supino, mani sotto i glutei per proteggere la lombare.",
      "Gambe tese unite e sollevate dal pavimento di pochi cm.",
      "Solleva le gambe fino a formare 90° con il busto.",
      "Scendi lentamente senza toccare terra.",
    ],
    tips: ["Lombare a terra", "Niente slancio", "Movimento controllato"],
    workSeconds: 35,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "📐",
  },
  {
    id: "side-plank",
    name: "Plank laterale",
    category: "core",
    short: "Obliqui e stabilità laterale",
    description:
      "Isometrico che attiva gli obliqui e il quadrato dei lombi. Migliora la stabilità laterale del bacino.",
    steps: [
      "Sdraiati su un fianco, gomito sotto la spalla.",
      "Solleva il bacino formando una linea retta dalla testa ai piedi.",
      "Mantieni l'altro braccio teso verso l'alto o sul fianco.",
      "Esegui per il tempo previsto e cambia lato.",
    ],
    tips: ["Non far cadere il bacino", "Spalla sopra al gomito", "Respira normalmente"],
    workSeconds: 30,
    restSeconds: 15,
    rounds: 4,
    poseTarget: "any",
    emoji: "📏",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "core",
    short: "Core profondo e coordinazione",
    description:
      "Attiva il core profondo in modo sicuro per la lombare. Migliora la coordinazione tra arti superiori e inferiori.",
    steps: [
      "Supino, braccia tese verso il soffitto, ginocchia piegate a 90°.",
      "Estendi contemporaneamente braccio destro indietro e gamba sinistra avanti.",
      "Torna alla posizione di partenza.",
      "Alterna mantenendo la lombare premuta a terra.",
    ],
    tips: ["Lombare sempre a terra", "Movimento lento", "Espira durante l'estensione"],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🪲",
  },
  {
    id: "hollow-hold",
    name: "Hollow Hold",
    category: "core",
    short: "Isometrico avanzato",
    description:
      "Posizione isometrica che attiva intensamente tutto il retto addominale. Base della ginnastica.",
    steps: [
      "Sdraiati supino, braccia tese sopra la testa.",
      "Solleva contemporaneamente spalle e gambe dal pavimento.",
      "Mantieni la lombare premuta a terra.",
      "Tieni la posizione respirando normalmente.",
    ],
    tips: ["Lombare schiacciata a terra", "Mento leggermente retratto", "Niente apnea"],
    workSeconds: 25,
    restSeconds: 25,
    rounds: 4,
    poseTarget: "any",
    emoji: "🛶",
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    category: "core",
    short: "Addominali e obliqui dinamico",
    description:
      "Combina crunch e rotazione per attivare retto addominale e obliqui contemporaneamente.",
    steps: [
      "Supino, mani dietro la nuca, gambe sollevate a 90°.",
      "Porta il gomito destro al ginocchio sinistro estendendo l'altra gamba.",
      "Alterna con un movimento di pedalata.",
      "Mantieni il ritmo costante e controllato.",
    ],
    tips: ["Non tirare il collo", "Ruota dal tronco", "Movimento ampio"],
    workSeconds: 35,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🚴",
  },

  // ============ FORZA ============
  {
    id: "diamond-pushup",
    name: "Piegamenti diamante",
    category: "forza",
    short: "Focus tricipiti",
    description:
      "Variante avanzata dei piegamenti con mani vicine. Massima attivazione dei tricipiti.",
    steps: [
      "Posizione di piegamento con pollici e indici uniti a formare un diamante.",
      "Mani sotto il petto, corpo in linea retta.",
      "Scendi mantenendo i gomiti vicini al corpo.",
      "Spingi tornando alla posizione iniziale.",
    ],
    tips: ["Gomiti aderenti al busto", "Corpo allineato", "Movimento controllato"],
    workSeconds: 30,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "pushup",
    emoji: "💎",
  },
  {
    id: "pike-pushup",
    name: "Pike Push-up",
    category: "forza",
    short: "Spalle e deltoidi",
    description: "Variante verticale dei piegamenti che simula la push press. Sviluppa i deltoidi.",
    steps: [
      "Posizione di V rovesciata: piedi e mani a terra, bacino in alto.",
      "Piega i gomiti portando la testa verso terra.",
      "Spingi tornando alla posizione iniziale.",
      "Mantieni le gambe tese durante tutto il movimento.",
    ],
    tips: ["Bacino alto", "Sguardo tra le mani", "Gomiti verso l'esterno"],
    workSeconds: 30,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "pushup",
    emoji: "🔺",
  },
  {
    id: "wide-pushup",
    name: "Piegamenti larghi",
    category: "forza",
    short: "Focus pettorali",
    description: "Variante a presa larga che enfatizza il lavoro del grande pettorale.",
    steps: [
      "Mani molto più larghe delle spalle, dita rivolte in avanti.",
      "Scendi piegando i gomiti verso l'esterno.",
      "Sfiora il petto a terra.",
      "Spingi tornando in alto.",
    ],
    tips: ["Apri il petto", "Scapole controllate", "Non far cadere i fianchi"],
    workSeconds: 35,
    restSeconds: 25,
    rounds: 3,
    poseTarget: "pushup",
    emoji: "🦅",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "forza",
    short: "Quadricipiti e glutei unilaterale",
    description:
      "Squat monopodalico con il piede posteriore rialzato. Esercizio molto efficace per gambe e glutei.",
    steps: [
      "Posiziona il piede posteriore su un rialzo (sedia, divano).",
      "Piede anteriore avanzato, busto eretto.",
      "Scendi piegando il ginocchio anteriore fino a 90°.",
      "Spingi sul tallone anteriore per risalire.",
    ],
    tips: ["Peso sul piede anteriore", "Ginocchio in linea con la punta", "Busto eretto"],
    workSeconds: 40,
    restSeconds: 25,
    rounds: 3,
    poseTarget: "any",
    emoji: "🇧🇬",
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    category: "forza",
    short: "Isometrico quadricipiti",
    description: "Isometrico contro il muro che sviluppa resistenza e forza dei quadricipiti.",
    steps: [
      "Schiena appoggiata al muro, piedi in avanti.",
      "Scendi fino a portare le cosce parallele al pavimento.",
      "Ginocchia a 90°, sopra i talloni.",
      "Mantieni la posizione respirando normalmente.",
    ],
    tips: ["Schiena ben appoggiata", "Peso sui talloni", "Non bloccare il respiro"],
    workSeconds: 45,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "any",
    emoji: "🧱",
  },
  {
    id: "calf-raise",
    name: "Sollevamento polpacci",
    category: "forza",
    short: "Polpacci e equilibrio",
    description: "Isolamento dei muscoli del polpaccio. Sviluppa forza e definizione.",
    steps: [
      "In piedi, piedi alla larghezza dei fianchi.",
      "Solleva i talloni andando in punta di piedi.",
      "Pausa di un secondo in alto contraendo i polpacci.",
      "Scendi lentamente.",
    ],
    tips: ["Massima estensione in alto", "Niente rimbalzi", "Eventualmente appoggiati a un muro"],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🦶",
  },
  {
    id: "superman",
    name: "Superman",
    category: "forza",
    short: "Catena posteriore",
    description: "Rinforza i muscoli della catena posteriore: lombari, glutei e dorsali.",
    steps: [
      "Sdraiati proni, braccia tese in avanti.",
      "Solleva contemporaneamente braccia, petto e gambe dal pavimento.",
      "Mantieni 2 secondi contraendo i glutei.",
      "Torna lentamente alla posizione iniziale.",
    ],
    tips: ["Sguardo a terra", "Non iperestendere il collo", "Movimento controllato"],
    workSeconds: 35,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🦸",
  },
  {
    id: "tricep-dip",
    name: "Dip per tricipiti",
    category: "forza",
    short: "Tricipiti con sedia",
    description: "Esercizio per tricipiti e deltoidi anteriori eseguibile con una sedia o panca.",
    steps: [
      "Siediti sul bordo di una sedia, mani ai lati con le dita rivolte in avanti.",
      "Sposta il bacino in avanti facendo scivolare il corpo fuori dalla sedia.",
      "Piega i gomiti scendendo fino a 90°.",
      "Spingi con i tricipiti per risalire.",
    ],
    tips: ["Gomiti verso dietro, non verso fuori", "Spalle basse", "Schiena vicina alla sedia"],
    workSeconds: 35,
    restSeconds: 25,
    rounds: 3,
    poseTarget: "any",
    emoji: "💺",
  },

  // ============ SCHIENA ============
  {
    id: "cobra",
    name: "Cobra",
    category: "schiena",
    short: "Estensione della colonna",
    description:
      "Asana yoga che allunga la zona lombare e apre il torace. Contrasta la postura curva.",
    steps: [
      "Sdraiati proni, mani a terra sotto le spalle.",
      "Spingi con le braccia sollevando il busto.",
      "Mantieni il bacino a terra e le spalle basse.",
      "Respira profondamente nella posizione.",
    ],
    tips: ["Spalle lontane dalle orecchie", "Bacino a terra", "Nessun dolore lombare"],
    workSeconds: 30,
    restSeconds: 15,
    rounds: 3,
    poseTarget: "any",
    emoji: "🐍",
  },
  {
    id: "child-pose",
    name: "Posizione del bambino",
    category: "schiena",
    short: "Decompressione lombare",
    description: "Posizione di rilassamento che allunga dolcemente la zona lombare e le anche.",
    steps: [
      "In ginocchio, siediti sui talloni.",
      "Piega il busto in avanti portando la fronte a terra.",
      "Braccia tese in avanti o lungo il corpo.",
      "Respira profondamente rilassando la schiena.",
    ],
    tips: ["Rilassa le spalle", "Respiri lunghi e profondi", "Allarga le ginocchia se serve"],
    workSeconds: 60,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🧒",
  },
  {
    id: "knee-to-chest",
    name: "Ginocchia al petto",
    category: "schiena",
    short: "Allungamento lombare",
    description:
      "Allunga la zona lombare e i glutei. Ottimo per scaricare tensioni dopo lunghe ore seduti.",
    steps: [
      "Supino, gambe distese.",
      "Porta un ginocchio al petto abbracciandolo.",
      "Mantieni l'altra gamba distesa a terra.",
      "Cambia gamba dopo qualche respiro.",
    ],
    tips: ["Rilassa le spalle", "Mantieni la lombare a terra", "Respira nella posizione"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 3,
    poseTarget: "any",
    emoji: "🦵",
  },
  {
    id: "thoracic-rotation",
    name: "Rotazione toracica",
    category: "schiena",
    short: "Mobilità dorsale",
    description:
      "Mobilizza il tratto dorsale, spesso rigido. Riduce dolori cervicali e tra le scapole.",
    steps: [
      "Quadrupedia, mano destra dietro la testa.",
      "Ruota il gomito verso il pavimento.",
      "Poi apri ruotando il gomito verso il soffitto.",
      "Esegui il movimento lentamente e alterna.",
    ],
    tips: ["Bacino stabile", "Sguardo segue il gomito", "Movimento ampio"],
    workSeconds: 40,
    restSeconds: 15,
    rounds: 3,
    poseTarget: "any",
    emoji: "🔄",
  },
  {
    id: "pelvic-tilt",
    name: "Pelvic Tilt",
    category: "schiena",
    short: "Attivazione lombare profonda",
    description:
      "Mobilità del bacino che attiva il trasverso dell'addome e libera tensioni lombari.",
    steps: [
      "Supino, ginocchia piegate, piedi a terra.",
      "Inclina il bacino premendo la lombare a terra.",
      "Poi inarca leggermente la lombare staccandola.",
      "Alterna lentamente seguendo il respiro.",
    ],
    tips: ["Movimento piccolo e controllato", "Glutei rilassati", "Niente forzature"],
    workSeconds: 40,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🪶",
  },
  {
    id: "sphinx",
    name: "Sfinge",
    category: "schiena",
    short: "Estensione dolce",
    description:
      "Versione più dolce del cobra. Estende la colonna senza eccessivo carico sui polsi.",
    steps: [
      "Proni, avambracci a terra paralleli, gomiti sotto le spalle.",
      "Solleva il busto puntellandoti sugli avambracci.",
      "Spalle basse e lontane dalle orecchie.",
      "Respira nella posizione mantenendo il bacino a terra.",
    ],
    tips: ["Spalle basse", "Petto aperto", "Bacino a terra"],
    workSeconds: 40,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🦁",
  },

  // ============ MOBILITA ============
  {
    id: "shoulder-roll",
    name: "Circonduzioni spalle",
    category: "mobilita",
    short: "Riscaldamento spalle",
    description: "Mobilizza le spalle in tutte le direzioni. Perfetto come riscaldamento.",
    steps: [
      "In piedi, braccia rilassate lungo il corpo.",
      "Esegui ampie circonduzioni delle spalle in avanti.",
      "Cambia direzione dopo metà tempo.",
      "Mantieni il respiro costante.",
    ],
    tips: ["Movimento ampio", "Spalle rilassate", "Niente fretta"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🔁",
  },
  {
    id: "wrist-mobility",
    name: "Mobilità polsi",
    category: "mobilita",
    short: "Per chi sta al PC",
    description: "Allunga e mobilizza i polsi, prevenendo dolori da uso del computer.",
    steps: [
      "Braccia tese in avanti, palmi verso l'alto.",
      "Con l'altra mano spingi delicatamente le dita verso il basso.",
      "Cambia direzione spingendo verso l'alto.",
      "Alterna i polsi.",
    ],
    tips: ["Movimento dolce", "Senza forzare", "Respira durante l'allungamento"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🖐️",
  },
  {
    id: "ankle-circles",
    name: "Circonduzioni caviglie",
    category: "mobilita",
    short: "Mobilità delle caviglie",
    description: "Migliora la mobilità delle caviglie, fondamentale per squat, corsa e equilibrio.",
    steps: [
      "Seduto o in piedi, solleva un piede da terra.",
      "Esegui ampie circonduzioni della caviglia.",
      "Cambia direzione dopo qualche giro.",
      "Cambia piede.",
    ],
    tips: ["Movimenti ampi", "Senza dolore", "Lentamente"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🦶",
  },
  {
    id: "hamstring-stretch",
    name: "Allungamento ischiocrurali",
    category: "mobilita",
    short: "Posteriore della coscia",
    description: "Allunga la parte posteriore delle cosce, spesso retratta nei sedentari.",
    steps: [
      "Seduto a terra, una gamba tesa, l'altra piegata.",
      "Piega il busto in avanti verso il piede della gamba tesa.",
      "Mantieni la schiena dritta.",
      "Mantieni la posizione e cambia gamba.",
    ],
    tips: ["Niente molleggi", "Schiena lunga", "Respira nello stretching"],
    workSeconds: 40,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🦿",
  },
  {
    id: "deep-squat-hold",
    name: "Squat profondo isometrico",
    category: "mobilita",
    short: "Mobilità anche e caviglie",
    description: "Posizione di squat profondo per mobilizzare anche, caviglie e zona lombare.",
    steps: [
      "Piedi alla larghezza delle spalle.",
      "Scendi in squat profondo, talloni a terra.",
      "Gomiti contro l'interno delle ginocchia.",
      "Mantieni la posizione respirando e aprendo le anche.",
    ],
    tips: ["Talloni a terra", "Petto alto", "Apri le ginocchia con i gomiti"],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "⛷️",
  },
  {
    id: "pigeon-pose",
    name: "Posizione del piccione",
    category: "mobilita",
    short: "Apertura profonda anche",
    description: "Asana yoga che apre intensamente le anche e allunga il piriforme.",
    steps: [
      "Quadrupedia, porta il ginocchio destro avanti dietro il polso destro.",
      "Estendi la gamba sinistra indietro.",
      "Scendi con il busto in avanti sulla gamba piegata.",
      "Mantieni la posizione e cambia lato.",
    ],
    tips: ["Bacino quadrato", "Senza forzare", "Respira profondamente"],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🕊️",
  },

  // ============ CORE AGGIUNTIVI ============
  {
    id: "v-up",
    name: "V-Up",
    category: "core",
    short: "Addominali completo dinamico",
    description:
      "Solleva contemporaneamente busto e gambe toccando le punte dei piedi. Attiva l'intero retto addominale.",
    steps: [
      "Sdraiati supino, braccia tese sopra la testa, gambe distese.",
      "Solleva busto e gambe simultaneamente portando le mani verso i piedi.",
      "Tocca le punte dei piedi formando una V.",
      "Scendi lentamente senza toccare terra.",
    ],
    tips: ["Non usare slancio", "Lombare a terra", "Movimento controllato"],
    workSeconds: 30,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "✌️",
  },
  {
    id: "scissor-kicks",
    name: "Scissor Kicks",
    category: "core",
    short: "Forbici addominali",
    description:
      "Movimento alternato delle gambe in sospensione per attivare il retto addominale inferiore.",
    steps: [
      "Supino, mani sotto i glutei, gambe sollevate di pochi cm.",
      "Solleva una gamba verso l'alto mentre l'altra scende.",
      "Alterna con un movimento di forbice continuo.",
      "Mantieni le gambe tese e la lombare a terra.",
    ],
    tips: ["Niente oscillazioni del bacino", "Gambe tese", "Ritmo costante"],
    workSeconds: 30,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "✂️",
  },
  {
    id: "toe-touches",
    name: "Toe Touches",
    category: "core",
    short: "Crunch alternato",
    description:
      "Crunch in cui alterni toccare il tallone opposto. Attiva obliqui e retto addominale.",
    steps: [
      "Supino, gambe tese verso il soffitto.",
      "Solleva le spalle e allunga il braccio destro verso il piede sinistro.",
      "Torna giù e ripeti con il braccio sinistro verso il piede destro.",
      "Continua alternando i lati.",
    ],
    tips: ["Non tirare il collo", "Movimento dal tronco", "Espira salendo"],
    workSeconds: 35,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "👣",
  },
  {
    id: "bear-crawl",
    name: "Bear Crawl",
    category: "core",
    short: "Core e coordinazione totale",
    description:
      "Camminata quadrupedia con ginocchia sospese. Attiva core, spalle e coordinazione.",
    steps: [
      "Quadrupedia, solleva leggermente le ginocchia da terra.",
      "Cammina in avanti muovendo braccio opposto e gamba.",
      "Mantieni il bacino basso e il core contratto.",
      "Esegui spostamenti avanti e indietro.",
    ],
    tips: ["Ginocchia basse", "Core contratto", "Spalle sopra i polsi"],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🐻",
  },
  {
    id: "side-crunch",
    name: "Crunch laterale",
    category: "core",
    short: "Obliqui in flessione laterale",
    description:
      "Crunch eseguito da seduto ruotando il busto verso un lato. Perfetto per gli obliqui.",
    steps: [
      "Siediti a terra, ginocchia piegate, piedi a terra.",
      "Inclina il busto indietro di 45°.",
      "Porta entrambe le mani verso il fianco destro contraendo l'obliquo.",
      "Torna al centro e ripeti verso sinistra.",
    ],
    tips: ["Ruota il tronco, non solo piega", "Schiena dritta", "Espira contraendo"],
    workSeconds: 30,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "↔️",
  },
  {
    id: "ab-wheel",
    name: "Ab Wheel Rollout",
    category: "core",
    short: "Core avanzato con ruota",
    description:
      "Esercizio avanzato che sfida intensamente il core con un movimento di estensione controllata.",
    steps: [
      "In ginocchio, tieni la ruota davanti a te.",
      "Rotola in avanti lentamente estendendo il corpo.",
      "Fermati prima di perdere la contrazione addominale.",
      "Tira indietro la ruota tornando alla posizione di partenza.",
    ],
    tips: ["Non inarcare la schiena", "Core sempre contratto", "Range ridotto all'inizio"],
    workSeconds: 30,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "any",
    emoji: "🛞",
  },

  // ============ FORZA AGGIUNTIVI ============
  {
    id: "jump-squat",
    name: "Jump Squat",
    category: "forza",
    short: "Potenza e plyometrics",
    description:
      "Variante esplosiva dello squat che sviluppa potenza nelle gambe e attivazione neuromuscolare.",
    steps: [
      "Posizione di squat, piedi alla larghezza delle spalle.",
      "Scendi in squat profondo caricando l'elastico.",
      "Spingi esplosivamente e salta dal pavimento.",
      "Atterra ammortizzando e vai direttamente nel prossimo squat.",
    ],
    tips: ["Atterraggio morbido", "Piedi a terra stabili", "Spingi sui talloni"],
    workSeconds: 30,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "squat",
    emoji: "🚀",
  },
  {
    id: "step-up",
    name: "Step Up",
    category: "forza",
    short: "Gambe e glutei con rialzo",
    description:
      "Sale su un gradino o rialzo per sviluppare forza monopodalica e attivare i glutei.",
    steps: [
      "Di fronte a un gradino o sedia stabile.",
      "Salita con un piede portando l'altro a seguire.",
      "Scendi controllato con la stessa gamba.",
      "Alterna gamba di partenza ad ogni ripetizione.",
    ],
    tips: ["Tutto il piede sul rialzo", "Busto eretto", "Non spingere con il piede di dietro"],
    workSeconds: 40,
    restSeconds: 25,
    rounds: 3,
    poseTarget: "any",
    emoji: "📶",
  },
  {
    id: "inchworm",
    name: "Inchworm",
    category: "forza",
    short: "Core, spalle e flessibilità",
    description:
      "Movimento a verme che allunga i posteriori e attiva spalle e core in modo dinamico.",
    steps: [
      "In piedi, piegati in avanti toccando terra con le mani.",
      "Cammina con le mani in avanti fino a posizione di plank.",
      "Fai un piegamento opzionale in plank.",
      "Cammina con le mani indietro tornando in piedi.",
    ],
    tips: ["Gambe il più tese possibile", "Core contratto in plank", "Movimento lento"],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🐛",
  },
  {
    id: "archer-pushup",
    name: "Archer Push-up",
    category: "forza",
    short: "Piegamento asimmetrico avanzato",
    description:
      "Variante avanzata che concentra il carico su un braccio alla volta, preparando la one-arm push-up.",
    steps: [
      "Posizione di piegamento con mani molto larghe.",
      "Scendi piegando un gomito mentre l'altro resta quasi teso.",
      "Il braccio teso funge da supporto laterale.",
      "Alterna il lato dominante ad ogni ripetizione.",
    ],
    tips: ["Braccio di supporto quasi teso", "Busto in linea", "Range completo dal lato piegato"],
    workSeconds: 30,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "pushup",
    emoji: "🏹",
  },
  {
    id: "tuck-jump",
    name: "Tuck Jump",
    category: "forza",
    short: "Potenza esplosiva e cardio",
    description:
      "Salto verticale portando le ginocchia al petto. Sviluppa potenza e cardio in modo intenso.",
    steps: [
      "In piedi, piedi alla larghezza dei fianchi.",
      "Salta esplosivamente portando entrambe le ginocchia al petto.",
      "Ammortizza l'atterraggio sulle punte e poi talloni.",
      "Ripeti immediatamente il salto successivo.",
    ],
    tips: ["Braccia che spingono verso il basso", "Atterraggio morbido", "Core contratto"],
    workSeconds: 25,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "any",
    emoji: "🦘",
  },

  // ============ SCHIENA AGGIUNTIVI ============
  {
    id: "prone-ytw",
    name: "Prone Y-T-W",
    category: "schiena",
    short: "Rinforzo scapolare e postura",
    description:
      "Sequenza di movimenti proni per rinforzare i muscoli della scapola e correggere la postura curva.",
    steps: [
      "Sdraiati proni, fronte a terra, braccia tese in avanti (Y).",
      "Solleva le braccia in alto formando una Y, poi scendi.",
      "Porta le braccia a 90° lateralmente (T), solleva e scendi.",
      "Piega i gomiti a 90° (W), solleva e scendi.",
    ],
    tips: ["Spalle basse", "Non inarcare il collo", "Movimento lento e controllato"],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🔤",
  },
  {
    id: "mckenzie",
    name: "Estensione McKenzie",
    category: "schiena",
    short: "Riallineamento lombare",
    description:
      "Esercizio terapeutico che promuove l'estensione lombare, spesso consigliato per ernie discali lievi.",
    steps: [
      "Sdraiati proni, mani sotto le spalle come per il cobra.",
      "Spingi con le braccia sollevando il busto, bacino a terra.",
      "Mantieni il bacino ben a contatto con il pavimento.",
      "Rilassa e ripeti il movimento lentamente.",
    ],
    tips: [
      "Bacino sempre a terra",
      "Nessun dolore irradiato",
      "Consulta un terapista se necessario",
    ],
    workSeconds: 30,
    restSeconds: 15,
    rounds: 3,
    poseTarget: "any",
    emoji: "🦘",
  },
  {
    id: "thread-needle",
    name: "Thread the Needle",
    category: "schiena",
    short: "Rotazione toracica e stretch",
    description:
      "Esercizio yoga che mobilizza la colonna toracica con una rotazione controllata in quadrupedia.",
    steps: [
      "Quadrupedia, mani sotto le spalle.",
      "Solleva il braccio destro verso il soffitto aprendo il torace.",
      "Porta il braccio destro sotto il sinistro appoggiando la spalla a terra.",
      "Mantieni lo stretch e ripeti dall'altro lato.",
    ],
    tips: ["Bacino stabile", "Guarda verso il soffitto in apertura", "Respiri profondi"],
    workSeconds: 40,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🪡",
  },
  {
    id: "seated-twist",
    name: "Torsione seduta",
    category: "schiena",
    short: "Rotazione colonna completa",
    description:
      "Torsione della colonna in posizione seduta che allunga i muscoli paravertebrali e mobilizza il tronco.",
    steps: [
      "Siediti a terra con le gambe distese.",
      "Piega il ginocchio destro e porta il piede fuori della coscia sinistra.",
      "Ruota il busto verso destra appoggiando il gomito contro il ginocchio.",
      "Mantieni e cambia lato.",
    ],
    tips: [
      "Allunga la colonna prima di ruotare",
      "Respira approfondendo la torsione",
      "Senza forzare",
    ],
    workSeconds: 40,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🌀",
  },
  {
    id: "standing-cat-cow",
    name: "Gatto-Mucca in piedi",
    category: "schiena",
    short: "Mobilità schiena in stazione eretta",
    description:
      "Versione in piedi del cat-cow, ideale per chi non può mettersi a terra. Mobilizza la colonna in modo dolce.",
    steps: [
      "In piedi, ginocchia leggermente piegate, mani sui ginocchi.",
      "Inspira inarcando la schiena e guardando in su (mucca).",
      "Espira arrotondando la schiena e chinando il mento (gatto).",
      "Alterna seguendo il ritmo del respiro.",
    ],
    tips: ["Movimento fluido", "Sincronizza con il respiro", "Rilassa le spalle"],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🐈",
  },

  // ============ MOBILITÀ AGGIUNTIVI ============
  {
    id: "arm-circles",
    name: "Circonduzioni braccia",
    category: "mobilita",
    short: "Riscaldamento spalle e braccia",
    description:
      "Semplici circonduzioni delle braccia per mobilizzare spalle, pettorali e articolazioni.",
    steps: [
      "In piedi, braccia tese ai lati.",
      "Esegui ampie circonduzioni in avanti.",
      "Dopo metà tempo inverti la direzione all'indietro.",
      "Aumenta progressivamente il diametro del cerchio.",
    ],
    tips: ["Spalle rilassate", "Movimento ampio", "Respira costantemente"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "⭕",
  },
  {
    id: "hip-circles",
    name: "Circonduzioni bacino",
    category: "mobilita",
    short: "Mobilità articolare del bacino",
    description:
      "Movimento circolare del bacino per sciogliere tensioni lombari e migliorare la mobilità del bacino.",
    steps: [
      "In piedi, mani sui fianchi.",
      "Esegui grandi circonduzioni del bacino in senso orario.",
      "Cambia direzione dopo metà tempo.",
      "Coinvolgi anche il torace per un cerchio ampio.",
    ],
    tips: ["Gambe leggermente piegate", "Movimento ampio", "Rilassa il bacino"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🔄",
  },
  {
    id: "doorway-stretch",
    name: "Stretch al muro/porta",
    category: "mobilita",
    short: "Apertura pettorali",
    description:
      "Allunga il petto e i pettorali usando lo stipite di una porta per una trazione passiva.",
    steps: [
      "Posizionati di fianco a uno stipite con il gomito a 90°.",
      "Appoggia l'avambraccio sullo stipite, piede avanzato.",
      "Ruota il busto verso il lato opposto sentendo l'allungamento.",
      "Mantieni e cambia lato.",
    ],
    tips: ["Gomito a 90°", "Petto in avanti", "Senza forzare"],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🚪",
  },
  {
    id: "butterfly",
    name: "Farfalla seduta",
    category: "mobilita",
    short: "Apertura interno cosce",
    description:
      "Stretch per l'adduttore e l'interno delle cosce. Favorisce l'apertura del bacino.",
    steps: [
      "Siediti a terra, unisci le piante dei piedi davanti a te.",
      "Porta i talloni il più vicino possibile al perineo.",
      "Appoggia le mani sulle ginocchia e spingi delicatamente verso il basso.",
      "Mantieni la schiena dritta e respira.",
    ],
    tips: ["Schiena lunga", "Non forzare le ginocchia", "Respira allungando"],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🦋",
  },
  {
    id: "standing-quad",
    name: "Quadricipite in piedi",
    category: "mobilita",
    short: "Stretch quadricipite statico",
    description:
      "Allunga il quadricipite in stazione eretta, utile prima e dopo l'attività fisica.",
    steps: [
      "In piedi, appoggiati a una parete o sedia se necessario.",
      "Piega il ginocchio destro portando il tallone verso i glutei.",
      "Afferra il piede con la mano destra mantenendo ginocchio in linea.",
      "Mantieni e cambia gamba.",
    ],
    tips: [
      "Ginocchio in linea verticale",
      "Busto eretto",
      "Spingi leggermente il bacino in avanti",
    ],
    workSeconds: 30,
    restSeconds: 10,
    rounds: 2,
    poseTarget: "any",
    emoji: "🦵",
  },
  {
    id: "worlds-greatest",
    name: "World's Greatest Stretch",
    category: "mobilita",
    short: "Stretch totale dinamico",
    description:
      "Movimento dinamico che apre anche, flessori e torace in un unico flusso. Considerato uno degli stretch più completi.",
    steps: [
      "Posizione di affondo con mano destra a terra all'interno del piede.",
      "Appoggia l'avambraccio destro a terra per aprire l'anca.",
      "Ruota il busto verso l'alto portando il braccio destro verso il soffitto.",
      "Torna indietro, cambia gamba e ripeti.",
    ],
    tips: ["Movimento fluido", "Respira in ogni fase", "Apri bene il torace in rotazione"],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🌍",
  },
  {
    id: "jumping-jacks",
    name: "Jumping Jacks",
    category: "cardio",
    short: "Riscaldamento total body",
    description:
      "Esercizio cardio base che coinvolge tutto il corpo, ottimo per alzare il battito cardiaco.",
    steps: [
      "Parti in piedi con i piedi uniti e le braccia lungo i fianchi.",
      "Salta allargando le gambe e sollevando le braccia sopra la testa.",
      "Salta di nuovo per tornare alla posizione di partenza.",
      "Ripeti il movimento in modo continuo e fluido.",
    ],
    tips: [
      "Mantieni l'addome contratto",
      "Ammonizza l'atterraggio sulle punte dei piedi",
      "Respira ritmicamente",
    ],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "🤸‍♂️",
  },
  {
    id: "burpees",
    name: "Burpees",
    category: "cardio",
    short: "Condizionamento metabolico",
    description: "Un esercizio esplosivo per tutto il corpo che combina squat, piegamenti e salti.",
    steps: [
      "Inizia in piedi, poi scendi in posizione di squat poggiando le mani a terra.",
      "Lancia i piedi all'indietro per arrivare in posizione di plank.",
      "Esegui un piegamento sulle braccia (opzionale).",
      "Riporta i piedi in avanti con un salto e fai un salto esplosivo verso l'alto battendo le mani.",
    ],
    tips: [
      "Mantieni la schiena dritta",
      "Movimenti esplosivi",
      "Puoi saltare la flessione se è troppo difficile",
    ],
    workSeconds: 30,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "any",
    emoji: "🔥",
  },
  {
    id: "high-knees",
    name: "Skip a ginocchia alte",
    category: "cardio",
    short: "Corsa sul posto intensa",
    description:
      "Corsa sul posto ad alta intensità sollevando le ginocchia il più possibile per stimolare il sistema cardiovascolare.",
    steps: [
      "Corri sul posto portando alternativamente le ginocchia verso il petto.",
      "Le ginocchia dovrebbero arrivare almeno all'altezza dei fianchi.",
      "Usa le braccia per darti lo slancio e mantenere il ritmo.",
      "Atterra dolcemente sugli avampiedi.",
    ],
    tips: [
      "Busto dritto e petto in fuori",
      "Muovi le braccia in sincronia",
      "Ritmo veloce e costante",
    ],
    workSeconds: 30,
    restSeconds: 15,
    rounds: 4,
    poseTarget: "any",
    emoji: "🏃",
  },
  {
    id: "skater-jumps",
    name: "Pattinatore (Skater Jumps)",
    category: "cardio",
    short: "Salti laterali",
    description:
      "Esercizio cardio che mima il movimento del pattinaggio su ghiaccio. Ottimo per agilità, equilibrio e resistenza.",
    steps: [
      "Inizia in piedi, fai un ampio salto laterale verso destra atterrando sul piede destro.",
      "Incrocia la gamba sinistra dietro la destra senza toccare terra.",
      "Spingi sul piede destro per saltare lateralmente verso sinistra.",
      "Atterra sul piede sinistro e incrocia il destro dietro, mantenendo un ritmo fluido.",
    ],
    tips: ["Ammortizza l'atterraggio", "Usa le braccia per bilanciarti", "Mantieni il petto alto"],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "any",
    emoji: "⛸️",
  },
  {
    id: "butt-kicks",
    name: "Corsa calciata dietro",
    category: "cardio",
    short: "Riscaldamento dinamico",
    description:
      "Corsa sul posto in cui i talloni vanno a toccare i glutei. Ottimo per riscaldare i femorali e aumentare i battiti.",
    steps: [
      "Corri sul posto mantenendo le ginocchia puntate verso il basso.",
      "Porta i talloni alternativamente verso i glutei.",
      "Usa le braccia in modo coordinato, come nella corsa normale.",
      "Mantieni un ritmo rapido e leggero sugli avampiedi.",
    ],
    tips: ["Mantieni il busto dritto", "Non inarcare la schiena", "Respira regolarmente"],
    workSeconds: 40,
    restSeconds: 15,
    rounds: 3,
    poseTarget: "any",
    emoji: "🏃‍♀️",
  },
  {
    id: "jump-rope-sim",
    name: "Salto con la corda simulato",
    category: "cardio",
    short: "Cardio a basso impatto",
    description:
      "Riproduce il movimento del salto con la corda senza attrezzi. Eccellente per coordinazione e fiato.",
    steps: [
      "Tieni i piedi uniti e i gomiti vicini ai fianchi.",
      "Fai dei piccoli saltelli continui rimanendo sulle punte dei piedi.",
      "Fai ruotare i polsi in avanti come se tenessi una corda.",
      "Mantieni un ritmo costante e un movimento fluido.",
    ],
    tips: [
      "Salti bassi e veloci",
      "Mantieni le spalle rilassate",
      "Ruota solo i polsi, non tutte le braccia",
    ],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 4,
    poseTarget: "any",
    emoji: "🪢",
  },
  {
    id: "plank-jacks",
    name: "Plank Jacks",
    category: "core",
    short: "Core dinamico con salti",
    description: "Combina il plank con i jumping jacks, aumentando la frequenza cardiaca.",
    steps: [
      "Inizia in posizione di plank alto (sulle mani) o basso (sugli avambracci).",
      "Mantieni il core contratto e la schiena dritta.",
      "Salta allargando le gambe verso l'esterno.",
      "Salta di nuovo riportando i piedi uniti.",
    ],
    tips: [
      "Non sollevare il bacino",
      "Ammortizza i salti",
      "Mantieni le spalle sopra i polsi/gomiti",
    ],
    workSeconds: 30,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "plank",
    emoji: "⭐",
  },
  {
    id: "reverse-crunch",
    name: "Reverse Crunch",
    category: "core",
    short: "Addominali bassi concentrati",
    description:
      "Focalizzato sulla parte inferiore del retto addominale, ottimo per la zona bassa del core.",
    steps: [
      "Sdraiati a terra con le mani lungo i fianchi o sotto i glutei.",
      "Solleva le gambe piegandole a 90 gradi o mantenendole dritte.",
      "Contrai gli addominali per sollevare il bacino da terra verso il petto.",
      "Abbassa il bacino lentamente e in modo controllato.",
    ],
    tips: [
      "Non usare lo slancio",
      "Usa gli addominali per alzare il bacino",
      "Non inarcare la zona lombare in discesa",
    ],
    workSeconds: 40,
    restSeconds: 20,
    rounds: 3,
    poseTarget: "crunch",
    emoji: "🔄",
  },
  {
    id: "spiderman-pushup",
    name: "Spiderman Push-up",
    category: "forza",
    short: "Piegamenti con flessione laterale",
    description:
      "Aggiunge un movimento del ginocchio verso il gomito durante la flessione, attivando maggiormente core e obliqui.",
    steps: [
      "Inizia in posizione di plank alto.",
      "Mentre scendi in un piegamento, porta il ginocchio destro verso il gomito destro.",
      "Spingi verso l'alto riportando il piede alla posizione di partenza.",
      "Ripeti dall'altro lato (ginocchio sinistro al gomito sinistro).",
    ],
    tips: [
      "Guarda avanti",
      "Mantieni il corpo in linea",
      "Il ginocchio deve toccare o avvicinarsi molto al gomito",
    ],
    workSeconds: 30,
    restSeconds: 30,
    rounds: 3,
    poseTarget: "pushup",
    emoji: "🕷️",
  },
  {
    id: "squat-jump",
    name: "Squat Jump",
    category: "cardio",
    short: "Potenza e resistenza",
    description:
      "Variante esplosiva dello squat che aumenta la frequenza cardiaca e sviluppa la potenza delle gambe.",
    steps: [
      "Esegui un normale squat abbassando il bacino.",
      "Dal punto più basso, esplodi verso l'alto in un salto.",
      "Usa le braccia per darti lo slancio verso l'alto.",
      "Atterra dolcemente ammortizzando l'impatto ritornando subito in squat.",
    ],
    tips: [
      "Ammortizza bene in discesa",
      "Spingi forte con i piedi per saltare",
      "Mantieni il petto alto",
    ],
    workSeconds: 30,
    restSeconds: 20,
    rounds: 4,
    poseTarget: "squat",
    emoji: "🚀",
  },
  {
    id: "downward-dog",
    name: "Cane a testa in giù",
    category: "mobilita",
    short: "Allungamento della catena posteriore",
    description:
      "Posizione classica dello yoga ottima per allungare polpacci, femorali, schiena e spalle.",
    steps: [
      "Parti dalla posizione di quadrupedia (mani e ginocchia a terra).",
      "Punta le dita dei piedi e solleva il bacino verso l'alto spingendo con le mani.",
      "Cerca di formare una V rovesciata col corpo.",
      "Spingi i talloni verso terra (non importa se non toccano) e allunga la schiena.",
    ],
    tips: [
      "Rilassa il collo",
      "Più importante avere la schiena dritta che le gambe tese",
      "Respira profondamente nel torace",
    ],
    workSeconds: 45,
    restSeconds: 15,
    rounds: 2,
    poseTarget: "any",
    emoji: "🐕",
  },
];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function getExercisesByCategory(cat: ExerciseCategory): Exercise[] {
  return EXERCISES.filter((e) => e.category === cat);
}

export function getCategory(id: string) {
  return CATEGORIES.find((c) => c.id === id);
}
