/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExerciseIdRouteImport } from './routes/exercise.$id'
import { Route as CategoryCatRouteImport } from './routes/category.$cat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseIdRoute = ExerciseIdRouteImport.update({
  id: '/exercise/$id',
  path: '/exercise/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCatRoute = CategoryCatRouteImport.update({
  id: '/category/$cat',
  path: '/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$cat': typeof CategoryCatRoute
  '/exercise/$id': typeof ExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$cat': typeof CategoryCatRoute
  '/exercise/$id': typeof ExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$cat': typeof CategoryCatRoute
  '/exercise/$id': typeof ExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/program'
    | '/sitemap.xml'
    | '/category/$cat'
    | '/exercise/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/program' | '/sitemap.xml' | '/category/$cat' | '/exercise/$id'
  id:
    | '__root__'
    | '/'
    | '/program'
    | '/sitemap.xml'
    | '/category/$cat'
    | '/exercise/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramRoute: typeof ProgramRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoryCatRoute: typeof CategoryCatRoute
  ExerciseIdRoute: typeof ExerciseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/$id': {
      id: '/exercise/$id'
      path: '/exercise/$id'
      fullPath: '/exercise/$id'
      preLoaderRoute: typeof ExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$cat': {
      id: '/category/$cat'
      path: '/category/$cat'
      fullPath: '/category/$cat'
      preLoaderRoute: typeof CategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramRoute: ProgramRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoryCatRoute: CategoryCatRoute,
  ExerciseIdRoute: ExerciseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
